### PR TITLE
add EaseAgent to OpenAPM Landscape

### PR DESCRIPTION
**Pull request by Oseenix**
add EaseAgent to OpenAPM Landscape

### CODE REVIEW

**Comment by Oseenix** [comment]
@mariusoe could you help to review the PR?

**Comment by mariusoe** [comment]
@tobiangerstein please take over

**Comment by Oseenix** [comment]
> @tobiangerstein please take over

@tobiangersteineager to receive your feedback.

**Comment by tobiangerstein** [comment]
Hi @Oseenix thank you very much for the contribution and please excuse the delay!

Your pull request looks good! The changes will be soon applied to the website.

I just have seen, that you are also offering a non-open-source monitoring solution **Ease Monitor**.

Is the easeAgent able to send data to **Ease Monitor**? 

If so you might consider adding **Ease Monitor** as commercial tool to the openAPM landscape.


Please check out the commerical tools here: https://github.com/openapm/landscape-model/tree/master/model/components/commercial

**Comment by Oseenix** [comment]
> Hi @Oseenix thank you very much for the contribution and please excuse the delay!
> 
> Your pull request looks good! The changes will be soon applied to the website.
> 
> I just have seen, that you are also offering a non-open-source monitoring solution **Ease Monitor**.
> 
> Is the easeAgent able to send data to **Ease Monitor**?
> 
> If so you might consider adding **Ease Monitor** as commercial tool to the openAPM landscape.
> 
> Please check out the commerical tools here: https://github.com/openapm/landscape-model/tree/master/model/components/commercial

@tobiangerstein  Thank you. Yes, the data is sent to EaseMonitor. We are also considering how to open source EaseMonitor, and the next step will be to make EaseAgent support plugin Reporter to support converting data to any other format and sending it to any data backend.

**Pull request merged**
